# Generated by Django 4.2 on 2023-04-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="edition",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
